### PR TITLE
Fix #29 - Division by Zero Exception

### LINKED ISSUE #29: divide by zero Problem
I get this error when using GifImageView with GridView using custom ImageAdapter extends BaseAdapter

12-02 16:06:56.619 15491-15601/? E/AndroidRuntime: FATAL EXCEPTION: Thread-3008
                                                   Process: vn.messengerkvtm.gs, PID: 15491
                                                   java.lang.ArithmeticException: divide by zero
                                                       at com.felipecsl.gifimageview.library.GifDecoder.advance(GifDecoder.java:229)
                                                       at com.felipecsl.gifimageview.library.GifImageView.run(GifImageView.java:157)
                                                       at java.lang.Thread.run(Thread.java:841)

[ImageAdapter.txt](https://github.com/felipecsl/GifImageView/files/49510/ImageAdapter.txt)

### PR DESCRIPTION
**Pull request by andrewlord1990**
Added Grid View activity to the sample:

1) To demonstrate / test lots of GIFs at once.
2) #29 was reported to occur in a GridView so made sense to test with it.

Fixes #29.

### CODE REVIEW

**Comment by felipecsl** [comment]
This is great. Thanks!

**Comment by andrewlord1990** [comment]
No problem!

**Comment by jaredsburrows** [comment]
@felipecsl Can you release an updated version of this lib? I am seeing this error frequently.

**Comment by felipecsl** [comment]
@jaredsburrows done, 2.1.0 released

**Comment by jaredsburrows** [comment]
@felipecsl Thank you!

**Pull request merged**
