### PR TITLE
Apply latest changes of glide gifdecoder, fix DISPOSE_BACKGROUND and DISPOSE_PREVIOUS

### PR DESCRIPTION
**Pull request by keewon**
Instead of https://github.com/felipecsl/GifImageView/pull/54 , submitting a new PR.

As @felipecsl mentioned, copied code block from https://github.com/bumptech/glide/blob/6ddb5f0598b1a5a5a51647fb968e998d6cabbd3d/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/StandardGifDecoder.java#L389-L392

Works well with my case, and also I hope it will fix https://github.com/felipecsl/GifImageView/issues/46 

Thanks.

### CODE REVIEW

**Comment by keewon** [comment]
Oops, I did it wrong again.
GifDecoder of glide checks `previousFrame == null`, while mine checks `previousImage == null`
Will add additional commits.

**Comment by keewon** [comment]
This was not a simple thing. https://github.com/bumptech/glide/issues/1094 is a related issue, but this is not yet merged even into the master branch of bumptech/glide . I will try this soon, but not today.

**Comment by keewon** [comment]
Before:
before

After:
after

**Comment by felipecsl** [comment]
This is awesome, thanks a lot for doing it @keewon. I'll cut a new release with these changes soon

**Comment by keewon** [comment]
Thanks a lot!

**Pull request merged**
