### PR TITLE
added custom frames display duration

### PR DESCRIPTION
**Pull request by donvigo**
Having possibility to set custom frames display duration is very useful feature, and it's used a lot.

### CODE REVIEW

**Comment by felipecsl** [comment]
can you give me an example of when you'd use this? I've seen cases of the gif running too fast/too slow before, but how would you know the exact frame duration it should use? Is it an information you already retrieved from somewhere else?

**Comment by donvigo** [comment]
Actually, I've had different gifs provided by designer, and opening them on PC provided more smoothness sometimes comparing to the library gif animation, but sometimes vice versa. Giving a possibility to change animation speed provides more flexibility ;)

**Comment by felipecsl** [comment]
got it. Thanks for the contribution.

**Comment by donvigo** [comment]
Thank you too :+1:

**Comment by felipecsl** [comment]
This has been released to maven central as version 1.2.0

**Pull request merged**
